### ISSUE TITLE
PERMISSION_DENIED

### ISSUE THREAD

**Issue by bitliner** [googleapis/nodejs-speech#766] opened 2021-06-20 21:30 UTC
This works normally

```
process.env.GOOGLE_APPLICATION_CREDENTIALS = path.join(__dirname, '../credentials/jwt.keys.json')

new speech.v1p1beta1.SpeechClient()
```

While instead the following throws "permission denied" error

```
process.env.GOOGLE_APPLICATION_CREDENTIALS = path.join(__dirname, '../credentials/jwt.keys.json')

const adaptationClient = new speech.v1p1beta1.AdaptationClient()

const parent = `projects/${projectId}/locations/us-west1`
const phraseSetId = 'any-id'

const phraseSetResponse = await adaptationClient.createPhraseSet({
    parent: parent,
    phraseSetId: phraseSetId,
    phraseSet: {
      boost: 10,
      phrases: [
        // { value: `Visit restaurants like ${customClassId}` }
        { value: 'my word' }
      ]
    }
  })
```

The following does not work neither:

```
 curl -X POST   -H "Authorization: Bearer $(gcloud auth --impersonate-service-account=$SA_EMAIL print-access-token)"   -H "Content-Type: application/json; charset=utf-8"   "https://speech.googleapis.com/v1p1beta1/projects/project-id/locations/global/phraseSets" -d '{"phraseSetId": "test-phrase-set-1"}'
```

where `project-id` is the name of my project.

In the error, it seems a default project id is used (32555940559) but that is not the id of the project I want to use (that is why there is the error)

**Comment by b-loved-dreamer** [comment] 2021-06-21 23:24
Hi @bitliner, thank you for filling this issue. I was unable to reproduce the issue you are experiencing. I want to point out that I have completed my project setup with the service account and downloaded the private JSON key, which I think might be part of the issue in your case, please [read](https://cloud.google.com/speech-to-text/docs/quickstart-client-libraries).

The first two lines should not invoke any response from the service because its not executing the request until it tries to create the ```PhraseSet```, which is where the request is made.  

The random number you get for the ```project_id``` is just an element of processing your code and therefore trivial with respect to error you're getting. 

Having said this, I think you can start by making sure you have setup your project on the developer console, created a service account, enable the service (speech), and created/downloaded the JSON file, which serves as your access token for the service you are attempting to use.

**Comment by b-loved-dreamer** [comment] 2021-06-29 15:45
Thank you for filing this issue. We provided feedback a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.

**Closed by b-loved-dreamer** 2021-06-29 15:45 UTC
Labels: api: speech, status: investigating
