### ISSUE TITLE
Facing Sox error on Google cloud platform when I am deploying this code.

### ISSUE THREAD

**Issue by Ayushimidha28** [googleapis/nodejs-speech#592] opened 2020-05-07 04:57 UTC
I have Sox installed on my pc, that's why this code is working fine.
But it is showing errors when I deploy this code on the Google cloud platform because of SoX.

I am working on the MicrophoneStream.js.
```
const recorder = require('node-record-lpcm16');

// Imports the Google Cloud client library
const speech = require('@google-cloud/speech');

// Creates a client
const client = new speech.SpeechClient();

/**
 * TODO(developer): Uncomment the following lines before running the sample.
 */
// const encoding = 'Encoding of the audio file, e.g. LINEAR16';
// const sampleRateHertz = 16000;
// const languageCode = 'BCP-47 language code, e.g. en-US';

const request = {
  config: {
    encoding: encoding,
    sampleRateHertz: sampleRateHertz,
    languageCode: languageCode,
  },
  interimResults: false, // If you want interim results, set this to true
};

// Create a recognize stream
const recognizeStream = client
  .streamingRecognize(request)
  .on('error', console.error)
  .on('data', data =>
    process.stdout.write(
      data.results[0] && data.results[0].alternatives[0]
        ? `Transcription: ${data.results[0].alternatives[0].transcript}\n`
        : '\n\nReached transcription time limit, press Ctrl+C\n'
    )
  );

// Start recording and send the microphone input to the Speech API.
// Ensure SoX is installed, see https://www.npmjs.com/package/node-record-lpcm16#dependencies
recorder
  .record({
    sampleRateHertz: sampleRateHertz,
    threshold: 0,
    // Other options, see https://www.npmjs.com/package/node-record-lpcm16#options
    verbose: false,
    recordProgram: 'rec', // Try also "arecord" or "sox"
    silence: '10.0',
  })
  .stream()
  .on('error', console.error)
  .pipe(recognizeStream);

console.log('Listening, press Ctrl+C to stop.');

```

**Comment by gguuss** [comment] 2020-05-12 18:19
Can you tell us what the errors are?
Also, which code / sample are you running?

I just navigated to cloud shell and ran the following commands:

```
git clone https://github.com/googleapis/nodejs-speech
cd nodejs-speech/samples
npm install
node quickstart.js
```

So I'm not sure where you're seeing the issue.

**Comment by Ayushimidha28** [comment] 2020-05-13 06:00
```
Error: spawn sox ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```


I am receiving this error on Google cloud platform when I am trying to deploy.

**Comment by Ayushimidha28** [comment] 2020-05-13 07:14
![sox error](https://user-images.githubusercontent.com/29372393/81780065-81092980-9513-11ea-9412-96e3517d6b83.png)
This is the screenshot of the error I am getting.

**Comment by Ayushimidha28** [comment] 2020-05-25 07:29
This the content of my package.json file

{
  "name": "new-express-app",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node index.js",
    "dev": "nodemon index.js"
  },
  "dependencies": {
    "@google-cloud/speech": "^3.6.0",
    "actions-on-google": "^2.7.0",
    "axios": "^0.19.0",
    "body-parser": "~1.18.2",
    "child_process": "^1.0.2",
    "cors": "^2.8.4",
    "dialogflow": "^0.9.0",
    "dialogflow-fulfillment": "^0.6.1",
    "express": "^4.17.1",
    "google-oauth-jwt": "^0.2.0",
    "gyp": "^0.5.0",
    "in": "^0.17.0",
    "line": "^0.1.8",
    "moment": "^2.24.0",
    "mongoose": "^5.6.8",
    "node-gyp": "^6.1.0",
    "node-record-lpcm16": "^1.0.1",
    "nodemailer": "^6.3.0",
    "nodemon": "^2.0.3",
    "pm2": "^4.2.3",
    "rebuild": "^0.1.2",
  
    "yargs": "^15.3.1"
  },
  "main": "index.js",
  "devDependencies": {},
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": ""
}

**Comment by munkhuushmgl** [comment] 2020-05-27 19:27
Hmm, looks like reproducing this error requires deploying something similar to GCP.

**Comment by munkhuushmgl** [comment] 2020-05-27 19:57
I think you forgot to include **sox dependency** in your package.json
```
  "dependencies": {
    "@google-cloud/speech": "^3.6.0",
    "chalk": "^4.0.0",
    "node-record-lpcm16": "^1.0.1",
    "sox": "^0.1.0",
....
```

I have tested Google Cloud Shell and it is working as intended.
![image](https://user-images.githubusercontent.com/45373284/83066137-72de0180-a019-11ea-8bc2-bd4c78b5cb9a.png)

Here's code snippet I used for testing
```

const fs = require('fs');

// Imports the Google Cloud client library
const speech = require('@google-cloud/speech');

// Creates a client
const client = new speech.SpeechClient();

/**
 * TODO(developer): Uncomment the following lines before running the sample.
 */
// const filename = 'Local path to audio file, e.g. /path/to/audio.raw';
// const encoding = 'Encoding of the audio file, e.g. LINEAR16';
// const sampleRateHertz = 16000;
// const languageCode = 'BCP-47 language code, e.g. en-US';

const request = {
  config: {
    encoding: 'LINEAR16',
    sampleRateHertz: 16000,
    languageCode: 'en-US',
  },
  interimResults: false, // If you want interim results, set this to true
};

// Stream the audio to the Google Cloud Speech API
const recognizeStream = client
  .streamingRecognize(request)
  .on('error', console.error)
  .on('data', data => {
    console.log(
      `Transcription: ${data.results[0].alternatives[0].transcript}`
    );
  });

// Stream an audio file from disk to the Speech API, e.g. "./resources/audio.raw"
fs.createReadStream('./audio.raw').pipe(recognizeStream);
```

**Comment by munkhuushmgl** [comment] 2020-05-27 19:58
@Ayushimidha28 Please let me know if this solves the problem.

**Comment by Ayushimidha28** [comment] 2020-05-29 05:16
> Can you tell us what the errors are?
> Also, which code / sample are you running?
> 
> I just navigated to cloud shell and ran the following commands:
> 
> ```
> git clone https://github.com/googleapis/nodejs-speech
> cd nodejs-speech/samples
> npm install
> node quickstart.js
> ```
> 
> So I'm not sure where you're seeing the issue.

I am Working on MicrophoneStream.js. In quickstart.js you are taking input from an audio file. I am taking input from microphone.

**Comment by munkhuushmgl** [comment] 2020-05-29 17:47
@Ayushimidha28 Hmm, including `MicrophoneStream` in your first question could've saved a lot of time. I will test it again with `MicrophoneStream`

**Comment by Ayushimidha28** [comment] 2020-06-01 04:55
> @Ayushimidha28 Hmm, including `MicrophoneStream` in your first question could've saved a lot of time. I will test it again with `MicrophoneStream`

I am extremely sorry. I have edited that now.

**Comment by munkhuushmgl** [comment] 2020-06-01 22:45
I was able to reproduce your error 
![image](https://user-images.githubusercontent.com/45373284/83456239-2d07ab80-a414-11ea-9e46-77ef80113c46.png)

 I need more info about how you are deploying your code to google cloud?

**Comment by munkhuushmgl** [comment] 2020-06-03 01:20
Since your app rely on Sox, you may need to use Docker Image that contains `sox` depending on how you want to deploy your app.
Here are some options:

- In GAE Flexible, you are always running at least 1 instance at any time. So even if your app is not getting any requests, you’re paying for that instance. Billing granularity is 1 minute.

- In Cloud Run, you are only paying when you are processing requests, and the billing granularity is 0.1 second. See here for an explanation of the Cloud Run billing model.

**Comment by munkhuushmgl** [comment] 2020-06-03 01:21
@Ayushimidha28 Closing this issue because it is not related to nodejs speech.

**Closed by munkhuushmgl** 2020-06-03 01:21 UTC
Labels: api: speech, needs more info, type: question
