### ISSUE TITLE
Malordered Data Received. Send exactly one config, followed by audio data.

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-speech#170] opened 2018-09-14 14:58 UTC
## Originally posted in https://github.com/googleapis/nodejs-speech/issues/62#issuecomment-420943003

I've updated to v2.1.0 and I'm getting the following error (error event in `streamingRecognize()` returned instance:

```
[3 INVALID_ARGUMENT: Malordered Data Received. Send exactly one config, followed by audio data.]
```

Would you be so kind to respond these questions,

- How has the API changed for this error to happen?

- Is v2.1.0 stable or beta?

In summary. I just would like to upgrade to the fixed version and make it work as before.

Thanks

**Comment by stephenplusplus** [comment] 2018-09-14 14:59
@jmillan -- is [this repo](https://github.com/jmillan/NodeJsSpeechIssue62Simplified) still the one that will reproduce this error?

**Comment by jmillan** [comment] 2018-09-17 08:42
Hi, 

> @jmillan -- is this repo still the one that will reproduce this error?

Not in that repo.

Just run the tests of this (yes `nodejs-speech`) repo:

````
jmillan@Mac.local:~/src/nodejs-speech/samples (master)$ node recognize.js listen
Listening, press Ctrl+C to stop.
(node:45299) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
{ Error: 3 INVALID_ARGUMENT: Malordered Data Received. Send exactly one config, followed by audio data.
    at Object.exports.createStatusError (/Users/jmillan/src/nodejs-speech/samples/node_modules/grpc/src/common.js:87:15)
    at ClientDuplexStream._emitStatusIfDone (/Users/jmillan/src/nodejs-speech/samples/node_modules/grpc/src/client.js:235:26)
    at ClientDuplexStream._receiveStatus (/Users/jmillan/src/nodejs-speech/samples/node_modules/grpc/src/client.js:213:8)
    at Object.onReceiveStatus (/Users/jmillan/src/nodejs-speech/samples/node_modules/grpc/src/client_interceptors.js:1290:15)
    at InterceptingListener._callNext (/Users/jmillan/src/nodejs-speech/samples/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/Users/jmillan/src/nodejs-speech/samples/node_modules/grpc/src/client_interceptors.js:614:8)
    at /Users/jmillan/src/nodejs-speech/samples/node_modules/grpc/src/client_interceptors.js:1110:18
  code: 3,
  metadata: Metadata { _internal_repr: {} },
  details: 'Malordered Data Received. Send exactly one config, followed by audio data.' }
````

**Comment by kinwa91** [comment] 2018-09-17 23:11
Duplicate of #173

**Closed** 2018-09-21 15:45 UTC
Labels: :rotating_light:, priority: p1, status: duplicate, triage me, type: bug

**Comment by RaphiePS** [comment] 2021-02-04 17:14
Just to provide a little more context - I'm experiencing this both with my own code, and as a sanity check, with @vin-ni's Socket Playground [here](https://github.com/vin-ni/Google-Cloud-Speech-Node-Socket-Playground/issues/9).

I'm able to use my credentials for other Speech requests. So it seems like I can rule out my code being bad (in this specific case, hah) and my auth being bad. Strange stuff.
