### ISSUE TITLE
Long running operation has finished but there was no result

### ISSUE THREAD

**Issue by artz** [googleapis/nodejs-speech#330] opened 2019-04-03 21:50 UTC
I followed the [documentation on this page](https://cloud.google.com/speech-to-text/docs/async-recognize) and am getting the following error:

```bash
{ error:
   { Error: Long running operation has finished but there was no result
       at self.getOperation (/Users/artz/Sites/website/node_modules/@google-cloud/speech/node_modules/google-gax/build/src/longrunning.js:284:39)
       at Operation._unpackResponse (/Users/artz/Sites/website/node_modules/@google-cloud/speech/node_modules/google-gax/build/src/longrunning.js:228:13)
       at noCallbackPromise.currentCallPromise_.then.responses (/Users/artz/Sites/website/node_modules/@google-cloud/speech/node_modules/google-gax/build/src/longrunning.js:197:18) code: 2 } }
```
My full code is below:
```javascript
try {
    const [operation] = await speechClient.longRunningRecognize({
      config: {
        languageCode: 'en-US',
        encoding: 'OGG_OPUS',
        sampleRateHertz: 16000,
        model: 'video'
      },
      audio: {
        uri: `gs://${ video.bucket }/${ video.audio }`
      }
    })
    const [response] = await operation.promise()
    return response
} catch (error) {
  return { error }
}
```
I am testing with this file: http://assets.vizual.ai/audio/326c5427-4b03-4b37-a24d-4868198dbfb8.ogg

Any thoughts appreciated.

**Comment by krisalay** [comment] 2019-04-04 13:08
Even I am getting the same error for some audio files. I am using .flac as input from google cloud storage.

@artz , Did you find the solution for this issue?

**Comment by artz** [comment] 2019-04-04 14:28
@krisalay No, still waiting for a response. I will contact Google's support team and cross-reference this issue.

**Comment by krisalay** [comment] 2019-04-04 15:17
@artz , I used ffprobe to find the metadata for your audio file.
```
Input #0, mp3, from './arq.mp3':
  Metadata:
    encoder         : Lavf58.17.103
  Duration: 00:02:23.40, start: 0.023021, bitrate: 128 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc58.24
[FORMAT]
filename=./arq.mp3
nb_streams=1
nb_programs=0
format_name=mp3
format_long_name=MP2/3 (MPEG audio layer 2/3)
start_time=0.023021
duration=143.400000
size=2294637
bit_rate=128013
probe_score=51
TAG:encoder=Lavf58.17.103
```
It shows bit_rate = 128k, I changed it to 16k, and it works fine. Although the response, is not that accurate. Can you let me know which model (video, phone_call, default) are you using for the transcription?

**Comment by krisalay** [comment] 2019-04-04 15:27
@artz , I am not sure what will be the optimum bit_rate of audio file for better result from the google's speech to text.
If you find something about it, let me know.

**Comment by artz** [comment] 2019-04-04 18:46
I tried using the `video` and the `default` models, same results.  @krisalay are you thinking it's because the bit rate in the audio is too high?  Is this a bug or a feature? :)

**Comment by beccasaurus** [comment] 2019-04-04 19:46
Here are some [Best practices](https://cloud.google.com/speech-to-text/docs/best-practices) for recommendations on getting greater efficiency and accuracy –

https://cloud.google.com/speech-to-text/docs/best-practices

**Comment by krisalay** [comment] 2019-04-05 05:18
@beccasaurus, Thank you for the documentation for best practices.
But, nothing is specified about the optimum bit rate for the audio.
I have an audio file with 16k sampling & 8k bit rate, and it gives the same error "Long running operation has finished but there was no result".

**Comment by artz** [comment] 2019-04-05 15:42
@beccasaurus I read that documentation, but it doesn't mention bitrate, only sampling rate.  Do we need to be concerned with the bitrate as well?  It seems like 128k should work?

Also, is it normal to get "no results" or does that signify an error in the format?  Ideally the API would give some helpful error code to help me pinpoint the issue.

**Comment by artz** [comment] 2019-04-10 17:52
Still waiting for a resolution on this issue, is there another avenue of support for this service?  Unfortunately I will have to research other options if I can't get audio like the one provided transcribed.

**Comment by callmehiphop** [comment] 2019-04-10 21:11
I've been trying to dig into this a little and the results are a little confusing for me as well. I'm not actually able to reproduce the same error, however what I do see is the operation finishing with no results. This appears to happen via CLI as well as the Node client, so I have to assume this is backend specific. One thing to note is that in the Node client, my operation seems to hang indefinitely because the Operation completes but contains neither a result or an error, causing it to continue polling.

Inspecting the attached audio file I also noticed that the sample rate is 48000, however neither setting this value or resampling the file seems to matter. I have to assume the bit rate is the issue here as others have already pointed out, but I'm unable to find any documentation in the upstream API in regards to what it should be.

**Comment by krisalay** [comment] 2019-04-11 16:42
For some audio, we are getting results, but not for others. Still waiting for the issue to be resolved.
Also what does this error actually mean? Is there some issue with the audio or the service?

We are not able to figure out the exact solution.
@google-admin can you please reply with some solution, or the any other information regarding the error?

**Comment by krisalay** [comment] 2019-04-11 16:42
For some audio, we are getting results, but not for others. Still waiting for the issue to be resolved.
Also what does this error actually mean? Is there some issue with the audio or the service?

We are not able to figure out the exact solution.
@google-admin can you please reply with some solution, or the any other information regarding the error?

**Comment by maksimbykov** [comment] 2019-04-18 23:29
Any audio (more then 3 min length) give this err

**Comment by akgakgakg** [comment] 2019-04-20 13:15
I'm also getting this same error for almost all audio more than a few minutes long.

**Comment by sorokinvj** [comment] 2019-04-20 15:05
Hey guys, I've struggled with it several days, then I found out what was wrong – I uploaded my .ogg files to Google Storage with gzip: true. That was a problem. 

(I found this because when I deal only with streams - upload source to app -> convert to ffmpeg -> upload to storage, everything works fine, but when I started dealing with files and uploaded them with gzip - they produce the same error "Long running operation has finished but there was no result")

Hope it help!

**Comment by nnegrey** [comment] 2019-06-14 16:52
Howdy all, 

Question about Codec, are your audio files:
1. OGG VORBIS (not supported)
2. OGG_OPUS (supported)

**Comment by sorokinvj** [comment] 2019-06-14 17:40
> Howdy all,
> 
> Question about Codec, are your audio files:
> 
> 1. OGG VORBIS (not supported)
> 2. OGG_OPUS (supported)

mine is OPUS and everything is ok

**Comment by nnegrey** [comment] 2019-06-14 18:27
Going to close this as I'm assuming that is the issue, but if that is not, I'll keep investigating. 
:)

**Closed by nnegrey** 2019-06-14 18:27 UTC
Labels: type: question
