### ISSUE TITLE
Issue with infinite streaming errors DEADLINE_EXCEEDED after 1 minute

### ISSUE THREAD

**Issue by dweberlj** [googleapis/nodejs-speech#455] opened 2019-10-29 00:49 UTC
Hello,

I am having an issue with the infiniteStreaming.js example where after 1 minute of execution it errors with DEADLINE_EXCEEDED.  See screenshot below.  Since I had difficulties using the Sox microphone on Windows, I changed the infiniteStreaming.js code to stream a local WAV file to the Google engine.  The transcription from Google works great but only for 1 minute.  You can see in the console window that I display the start time and the time when it errors which is 1 min.

![image](https://user-images.githubusercontent.com/2339401/67728152-632a0c00-f9a9-11e9-83db-27aa9cb8ba82.png)

Here is the modified infiniteStreaming.js code, I simply commented out the recorder code and replaced it with fs.createReadStream

![image](https://user-images.githubusercontent.com/2339401/67728379-44784500-f9aa-11e9-9f90-f74f156edb0b.png)

For the audio input file I created a new WAV file using the /resources/commercial_mono.wav file and repeated it several times to get 22 minutes of audio.

Any help would be greatly appreciated.

Thanks,
Dean
[longaudiosample.zip](https://github.com/googleapis/nodejs-speech/files/3781201/longaudiosample.zip)

**Comment by bcoe** [comment] 2019-10-29 01:37
@callmehiphop I know you were helping folks earlier with a similar question related to long-lived requests on PubSub, is there a configuration setting that @dweberlj should be setting (or is this potentially a bug we should be addressing?)

**Comment by callmehiphop** [comment] 2019-10-29 19:03
@bcoe sounds like @dweberlj is hitting the [pre-configured deadline](https://github.com/googleapis/nodejs-speech/blob/master/src/v1/speech_client_config.json#L34), it would be great if gax allowed us to opt out of setting a deadline entirely, but since that isn't an option I think the best solution here would be to manually increase the deadline. 

```js
const stream = client.streamingRecognize(request, {
  timeout: 60000 * 5 // or longer if necessary..
});
```

**Comment by pvaillant** [comment] 2019-10-30 03:47
I just ran into this issue today also. Given that the limit was changed to 5 mins for v1p1beta1 on June 18/2019 (see https://cloud.google.com/speech-to-text/docs/release-notes), is there a reason to not just change the value in the config file to 300000 (5 mins in milliseconds)?

I manually changed my local file and I can confirm that the infiniteStreaming.js example works as expected with that one change.

**Comment by callmehiphop** [comment] 2019-10-30 06:53
Those files are generated so any manual edits we make will just get reverted, we would need some one on the API team to chime in here. 

I think we just need to make an amendment or two to the sample to make sure that the stream doesn't timeout like this.

**Comment by dweberlj** [comment] 2019-10-30 13:47
I also confirmed that the streaming timeout limit is 5 min (305 seconds).  See below error message and stack dump.  I agree that the infiniteStreaming example should be amended to automatically restart the stream on the timeout, and ideally have the streamingRecognize() API modified to support long / unlimited streams.

![image](https://user-images.githubusercontent.com/2339401/67862872-1f85ee00-fae0-11e9-9370-4f4b4c046a78.png)

![image](https://user-images.githubusercontent.com/2339401/67862815-1006a500-fae0-11e9-999e-b3356b9e82bf.png)

**Comment by flaeshik** [comment] 2019-11-10 21:29
As @callmehiphop suggested: 
> ```js
> const stream = client.streamingRecognize(request, {
>   timeout: 60000 * 5 // or longer if necessary..
> });
> ```

Unfortunately, this didn't work out for me. Amending the original `infiniteStreaming.js` with this small change still gets me `DEADLINE_EXCEEDED`.

**Comment by dweberlj** [comment] 2019-11-11 00:03
@callmehiphop I tried the same and it didn't work.  

The only way to get past 1 minute is to update the @google-cloud\speech\src\v1p1beta1\speech_client_config.json timeout_millis values to (60000*5) for 5 minutes.  

This is highly inadvisable and was only done to validate the limits in a test scenario.  I believe the only fix is up to the Google API team at this point.  Any suggestions would be greatly appreciated.

**Comment by bcoe** [comment] 2019-11-11 18:08
@callmehiphop @alexander-fenster @xiaozhenliu-gg5, I wonder if this might actually be a change in behavior when we moved from `grpc` to `@grpc/grpc-js`.

I believe the idea of the infinite streaming example is that, in application code, it times out requests before the gRPC timeout is raised, and then resumes where it's left off?

I think it might be worth confirming that this pattern works well with the existing gRPC transport libraries.

**Comment by bcoe** [comment] 2019-11-11 19:52
see: https://github.com/googleapis/nodejs-speech/issues/458

**Comment by b-loved-dreamer** [comment] 2021-05-19 22:34
This issue may no longer be relevant so I am closing it. Please reopen if needed.

**Closed by b-loved-dreamer** 2021-05-19 22:34 UTC
Labels: api: speech, type: question
