### ISSUE TITLE
Google speech API response timeout 

### ISSUE THREAD

**Issue by prashantmaheshwari94** [googleapis/nodejs-speech#45] opened 2018-03-22 10:56 UTC
Hi,

For certain audios, google speech API doesn't give a proper response. The request is getting timed out. 
To reproduce the issue you can pass an empty audio. Is there any workaround for it?

Thanks

**Comment by stephenplusplus** [comment] 2018-03-22 16:32
Could you show the code you're running, and version you're using? It will help us reproduce the issue, and ultimately diagnose the problem :)

**Comment by prashantmaheshwari94** [comment] 2018-03-23 06:16
function asyncRecognize(filename, encoding, sampleRateHertz, languageCode) {
  // [START speech_async_recognize]
  // Imports the Google Cloud client library
  const speech = require('@google-cloud/speech');
  const fs = require('fs');

  // Creates a client
  const client = new speech.SpeechClient();

  const config = {
    encoding: 'FLAC',
    sampleRateHertz: 16000,
    languageCode: 'en-IN',
  };
  const audio = {
    content: fs.readFileSync(filename).toString('base64'), // file is .flac
  };

  const request = {
    config: config,
    audio: audio,
  };

  // Detects speech in the audio file. This creates a recognition job that you
  // can wait for now, or get its result later.

  client
    .longRunningRecognize(request)
    .then(data => {
      const response = data[0];
      const operation = response;
      // Get a Promise representation of the final result of the job
      return operation.promise();
    })
    .then(data => {
      const response = data[0];
      const transcription = response.results
        .map(result => result.alternatives[0].transcript)
        .join('\n');
      console.log(`Transcription: ${transcription}`);
    })
    .catch(err => {
      console.error('ERROR:', err);
    });
  // [END speech_async_recognize]
}

I am using this function from samples/recognize.js in your repository

Google API version - @google-cloud/speech": "^1.0.1"
you can pass any audio with no utterances/words. the request will timeout.

Let me know if you need any other details.

**Comment by ottijp** [comment] 2018-03-26 06:31
I have similar issue too.
In my case with using event emitter pattern, `progress` events was emitted twice but no `complete` events was emitted.
(so the promise chain won't be either resolved or rejected.)

The REST API responses to the request was bellow.
(from parameters of callback to `progress` event.)

```
{
  "result": null,
  "name": "5622465609457788982",
  "metadata": {
    "startTime": {
      "seconds": "1522044952",
      "nanos": 558720000
    },
    "lastUpdateTime": {
      "seconds": "1522044953",
      "nanos": 111336000
    }
  },
  "done": false,
  "error": null,
  "response": null
}
```
```
{
  "result": null,
  "name": "5622465609457788982",
  "metadata": {
    "progressPercent": 100,
    "startTime": {
      "seconds": "1522044952",
      "nanos": 558720000
    },
    "lastUpdateTime": {
      "seconds": "1522044960",
      "nanos": 187001000
    }
  },
  "done": true,
  "error": null,
  "response": null
}
```

If `done` is true,  either `error` or `response` must be available.
https://cloud.google.com/speech/reference/rest/v1/operations

So I suspect Speech API has problem that it doesn't build `response` object in case of "no word audio".

**Comment by ottijp** [comment] 2018-03-26 08:44
I have another workaround.

```
client.longRunningRecognize(request)
  .then(responses => {
    const operation = responses[0]

    const errorHandler = err => {
      throw(err)
    }
    const completeHandler = longRRResponse => {
      // build text
      const text = longRRResponse.results.map((result) => {
        const alternative = result.alternatives[0]
        return `${alternative.transcript}\n`
      }).join('\n')
      console.log(text)
    }
    const progressHandler = (metadata, apiResponse) => {
      if (apiResponse.done && !apiResponse.response) {
        // progress with `done: true` means request completion
        operation.removeListener('error', errorHandler)
        operation.removeListener('complete', completeHandler)
        operation.removeListener('progress', progressHandler)
        console.log('(no text included in this audio)')
      }
    }
    operation.on('error', errorHandler)
    operation.on('complete', completeHandler)
    operation.on('progress', progressHandler)
  })
  .catch(err => {
    console.error(err)
  })
```

The point is `progressHandler`.

When all event listeners are removed, operation loop will be finished.
https://github.com/googleapis/gax-nodejs/blob/v0.16.0/lib/longrunning.js#L346-L348

**Comment by phsultan** [comment] 2018-03-26 10:33
Nice, it would stop even before waiting for a timeout. You might want to return an Error in the first promise without modifying nor adding `error` or `complete` handlers:

```
  client
    .longRunningRecognize(request)
    .then(data => {
      const response = data[0];
      const operation = response;

      operation.on('progress', function(metadata, apiResponse) {
        if (apiResponse.done && !apiResponse.response) {
          // progress with `done: true` means request completion
          throw new Error('No text included in this audio');
        }
      });

      // Get a Promise representation of the final result of the job
      return operation.promise();
    })
    .then(data => {
      const response = data[0];
      const transcription = response.results
        .map(result => result.alternatives[0].transcript)
        .join('\n');
      console.log(`Transcription: ${transcription}`);
    })
    .catch(err => {
      console.error('ERROR:', err);
    });
```

Anyhow, the issue should probably be fixed in https://github.com/googleapis/gax-nodejs, or on the server side. A similar issue there about how `progress` events are handled has been filed there : https://github.com/googleapis/gax-nodejs/issues/192

**Comment by stephenplusplus** [comment] 2018-03-26 13:27
@alexander-fenster could you loop in someone from the Speech team?:

> If done is true, either error or response must be available.
cloud.google.com/speech/reference/rest/v1/operations
>
> So I suspect Speech API has problem that it doesn't build response object in case of "no word audio".
>
> \- @ottijp https://github.com/googleapis/nodejs-speech/issues/45#issuecomment-376060147

**Comment by alexander-fenster** [comment] 2018-03-26 18:31
@stephenplusplus I've just asked Speech team.

**Comment by stephenplusplus** [comment] 2018-03-27 01:05
Here's a sample audio file: https://nofile.io/f/7bCgmbZ3Fxg/15-seconds-mono.flac

**Comment by xavicolomer** [comment] 2018-05-14 13:42
Funny thing is that if you check the operation after a while, it says 100 complete and done = true

`curl https://speech.googleapis.com/v1/operations/{NAME}?key={API_KEY}`

where NAME is included on the first Promise response.

So basically you can check if its finished, but you never get the transcription :__)

**Comment by stephenplusplus** [comment] 2018-05-16 19:05
@alexander-fenster did anyone ever get back to you on this?

**Comment by alexander-fenster** [comment] 2018-05-16 21:11
Oh, it looks they asked for a sample file and that's where I dropped the ball. @crwilcox can you follow up here please?

**Comment by pxpeterxu** [comment] 2018-06-12 08:46
Hey there! I'm running into this issue with this sample file that's never resolving with a promise:

https://drive.google.com/file/d/1TFJ1A8J5Y2EeNYU-COQr2kJvy4vopE6X/view?usp=sharing

Here's the code that I'm using:

```js
const config = {
  encoding: 'FLAC',
  languageCode: 'es-US',
  model: 'default',
};

const audio = {
  uri: 'URL_TO_FILE_IN_GCS',
};

const request = {
  config: config,
  audio: audio,
};

const [operation] = await speech.longRunningRecognize(request);
console.log(config);
console.log(operation);
setInterval(() => {
  operation.getOperation().then(data => {
    console.log('getOperation');
    console.log(data);
  });
}, 10000);
const [response] = await operation.promise();
console.log(response);
```

It seems like it's because the `result` we get back is `null`: this gets `console.log`'d by the `setInterval`

```
[ null,
  LongRunningRecognizeMetadata {
    progressPercent: 100,
    startTime: Timestamp { seconds: [Object], nanos: 60959000 },
    lastUpdateTime: Timestamp { seconds: [Object], nanos: 694858000 } },
  { result: null,
    name: '1256175250915529069',
    metadata:
     { typeUrl: 'type.googleapis.com/google.cloud.speech.v1p1beta1.LongRunningRe
cognizeMetadata',
       value: <Buffer 08 64 12 0b 08 a7 8e fe d8 05 10 98 d2 88 1d 1a 0c 08 aa 8
e fe d8 05 10 90 e2 aa cb 02> },
    done: true,
    error: null,
    response: null } ]
```

**Comment by kinwa91** [comment] 2018-12-14 21:34
There hasn't been an update on this issue, if there is any updates, please feel encouraged to reopen this issue.

**Closed by kinwa91** 2018-12-14 21:34 UTC
Labels: :rotating_light:, priority: p2, status: blocked, type: bug

**Comment by guillenvd** [comment] 2018-12-28 03:00
I'm working on something with Google speech API and I found the same Issue, my way to solve was to send an `emit` to the error listener  in that way break /stop the promise;
```
 operation.on('progress', (metadata, apiResponse) => {
        if (apiResponse.done && !apiResponse.response) {
          operation.emit('error');
        }
    });
```
